using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace BrawlStageManager {
	public static class SongsByStageID {
		#region mapping
		private static Dictionary<string, string[]> dict = new Dictionary<string, string[]>() {
			{"stgbattlefield", new string[] {
					("X04"),
					("T02"),
					("X25"),
					("W21"),
					("W23"),
			}},
			{"stgfinal", new string[] {
					("X05"),
					("T01"),
					("T03"),
					("W25"),
					("W31"),
			}},
			{"stgdolpic", new string[] {
					("A13"),
					("A07"),
					("A08"),
					("A14"),
					("A15"),
			}},
			{"stgmansion", new string[] {
					("A09"),
					("A06"),
					("A05"),
					("Q10"),
					("Q11"),
			}},
			{"stgkart", new string[] {
					("A20"),
					("A21"),
					("A22"),
					("A23"),
					("R05"),
					("R14"),
					("Q09"),
			}},
			{"stgjungle", new string[] {
					("B01"),
					("B08"),
					("B05"),
					("B06"),
					("B07"),
					("B10"),
					("B02"),
			}},
			{"stgoldin", new string[] {
					("C02"),
					("C09"),
					("C01"),
					("C04"),
					("C05"),
					("C08"),
					("C17"),
					("C18"),
					("C19"),
			}},
			{"stgpirates", new string[] {
					("C15"),
					("C16"),
					("C07"),
					("C10"),
					("C13"),
					("C11"),
					("C12"),
					("C14"),
			}},
			{"stgnorfair", new string[] {
					("D01"),
					("D03"),
					("D02"),
					("D05"),
					("R12"),
					("R07"),
			}},
			{"stgorpheon", new string[] {
					("D04"),
					("D08"),
					("D07"),
					("D06"),
					("D09"),
					("D10"),
			}},
			{"stgcrayon", new string[] {
					("E02"),
					("E07"),
					("E01"),
					("E03"),
					("E05"),
					("E06"),
			}},
			{"stghalberd", new string[] {
					("F06"),
					("F01"),
					("F05"),
					("F04"),
					("F02"),
					("F12"),
					("F07"),
					("F08"),
					("F03"),
					("F10"),
					("F09"),
					("F11"),
			}},
			{"stgstarfox", new string[] {
					("G10"),
					("G02"),
					("G01"),
					("G03"),
					("G04"),
					("G11"),
					("G05"),
					("G09"),
					("G07"),
					("G08"),
					("Q12"),
			}},
			{"stgstadium", new string[] {
					("H01"),
					("H03"),
					("H02"),
					("H04"),
					("H05"),
			}},
			{"stgtengan", new string[] {
					("H06"),
					("H08"),
					("H07"),
					("H09"),
					("H10"),
			}},
			{"stgfzero", new string[] {
					("I01"),
					("I03"),
					("I02"),
					("I04"),
					("I05"),
					("I06"),
					("I07"),
					("I08"),
					("I09"),
					("I10"),
					("R09"),
					("W18"),
			}},
			{"stgemblem", new string[] {
					("J02"),
					("J04"),
					("J08"),
					("J06"),
					("J07"),
					("J03"),
					("J13"),
					("J09"),
					("J10"),
					("J11"),
					("J12"),
					("W17"),
			}},
			{"stgmadein", new string[] {
					("M01"),
					("M02"),
					("M08"),
					("M07"),
					("M06"),
					("M05"),
					("M04"),
					("M03"),
					("M09"),
					("M10"),
					("M11"),
					("M12"),
					("M13"),
					("M15"),
					("M16"),
					("M17"),
					("M18"),
			}},
			{"stgearth", new string[] {
					("L06"),
					("L01"),
					("L07"),
					("L02"),
					("L04"),
					("L08"),
					("L05"),
					("L03"),
					("R08"),
			}},
			{"stgvillage", new string[] {
					("N01"),
					("N02"),
					("N03"),
					("N06"),
					("N05"),
					("N07"),
					("N08"),
					("N09"),
					("N10"),
					("N11"),
					("N12"),
			}},
			{"stgnewpork", new string[] {
					("K07"),
					("K09"),
					("K08"),
					("K10"),
					("K05"),
					("K01"),
			}},
			{"stgice", new string[] {
					("Q07"),
					("Q06"),
					("Q08"),
					("Q05"),
					("W13"),
			}},
			{"stgpalutena", new string[] {
					("P01"),
					("P03"),
					("P02"),
					("P04"),
			}},
			{"stgdonkey", new string[] {
					("B04"),
					("B03"),
					("B09"),
			}},
			{"stgfamicom", new string[] {
					("A17"),
					("Q02"),
					("Q01"),
					("Q13"),
					("Q14"),
			}},
			{"stggw", new string[] {
					("R04"),
					("Q04"),
					("W14"),
			}},
			{"stgpictchat", new string[] {
					("R02"),
					("R10"),
					("R11"),
					("R15"),
					("R16"),
					("R17"),
					("R13"),
					("R06"),
					("W20"),
			}},
			{"stgplankton", new string[] {
					("R03"),
			}},
			{"stgmetalgear", new string[] {
					("S06"),
					("S02"),
					("S03"),
					("S08"),
					("S04"),
					("S07"),
					("S05"),
					("S10"),
					("S11"),
			}},
			{"stggreenhill", new string[] {
					("U01"),
					("U04"),
					("U02"),
					("U03"),
					("U06"),
					("U07"),
					("U08"),
					("U09"),
					("U10"),
					("U11"),
					("U12"),
					("U13"),
			}},
			{"stgdxshrine", new string[] {
					("C03"),
					("W24"),
			}},
			{"stgdxyorster", new string[] {
					("W05"),
					("W15"),
			}},
			{"stgdxgarden", new string[] {
					("W03"),
					("W26"),
			}},
			{"stgdxonett", new string[] {
					("W12"),
					("W19"),
			}},
			{"stgdxcorneria", new string[] {
					("W08"),
					("W28"),
			}},
			{"stgdxrcruise", new string[] {
					("W02"),
					("W01"),
			}},
			{"stgdxgreens", new string[] {
					("W07"),
					("W06"),
			}},
			{"stgdxbigblue", new string[] {
					("W11"),
					("W29"),
			}},
			{"stgdxzebes", new string[] {
					("W27"),
					("W04"),
			}},
			{"stgdxpstadium", new string[] {
					("W09"),
					("W16"),
					("W10"),
			}},
			{"stgonlinetraining", new string[] {
					("X07"),
			}},
		};
		#endregion

		public static string[] ForPac(string filename) {
			filename = filename.ToLower();
			if (filename.StartsWith("stgmariopast_00")) {
				return new string[] {
					("A01"),
					("A16"),
					("A10"),
				};
			} else if (filename.StartsWith("stgmariopast_01")) {
				return new string[] {
					("A02"),
					("A03"),
					("A04"),
				};
			} else {
				string[] ret = null;
				string key = filename.Substring(0, filename.IndexOfAny("_.".ToCharArray()));
				dict.TryGetValue(key, out ret);
				return ret ?? new string[0];
			}
		}
	}
}
